global:
  scrape_interval: 15s   # Scrape targets every 15 seconds

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
  - job_name: 'gitlab'
    static_configs:
      - targets: ['gitlab:9168']
